<a href="https://colab.research.google.com/github/kthur/kthur/blob/master/programming/241028_ai_essential/%5BAI_Essential%5D_1028(%EB%B0%98)_%EC%8B%A4%EA%B8%B0%ED%8F%89%EA%B0%80_OOO_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AI Essential 실기 평가**

## [필독] **시험 주의 사항**

- 아래와 같이 **주석으로 구분된 곳에서 코드를 수정 및 작성** 해야하며, 표시된 곳 **이외의 코드 및 하이퍼파라미터 값을 임의로 수정하면 오답 처리 될 수 있습니다.**

```python
        # ================================================================== #
        #
        #                이 곳에서 코드를 수정 및 작성하세요.
        #
        # ================================================================== #
```

- 각 문제마다 **\[답안 작성\], \[답안 검증\]** 셀이 제공됩니다.
    - **\[제공 코드\]** : 답안 작성을 위해 기본적으로 제공되는 코드입니다.
    - **\[답안 작성\]** : 문제에 대한 답안을 작성하는 코드 셀로 문제를 읽고 코드를 구현합니다.
      - **답안 작성 셀을 삭제하거나 추가한 경우 실기 점수에 불이익이 있을 수 있습니다.**
    - **\[답안 검증\]** : 문제에 대한 답안을 중간 점검하기 위한 코드 셀로 출력 값이 다를 수 있습니다.
      - **해당 과정은 작성하신 답안의 정상 동작을 확인하는 과정으로 실기 점수(채점 결과)와는 연관이 없습니다.**

### 문제를 꼭 꼼꼼하게 읽고 코드를 작성해주세요. 실기시험의 부분 점수는 없으며 문제가 지시한 사항을 따르지 않는 경우 오답 처리 됩니다.

## **시험 환경 설정**
- 시험 응시를 위한 모듈을 설치합니다 아래 코드 셀을 실행하세요.

In [1]:
%%capture
!pip install JAEN -Uq

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchinfo import summary
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f'연산 장치 : {device}')

import JAEN
print(f'버전 확인 : {JAEN.__version__}')

- 필요시 추가 모듈(패키지)를 불러올 수 있습니다.

In [ ]:
# 여기에 추가 모듈을 불러서 사용하세요.


# **문제1. Leaky ReLU 활성화 함수 구현**

### **문제 설명**
- Leaky ReLU(Rectified Linear Unit) 활성화 함수는 ReLU의 변형으로, 음수 입력에 대해 작은 기울기를 가지도록 설계되었습니다. 이 함수는 비선형성을 제공하여 복잡한 문제를 해결하는 데 도움을 주며, 특히 경사 소실 문제를 완화하는 데 효과적입니다. Leaky ReLU는 양수 입력은 그대로 통과시키고, 음수 입력은 소량의 기여를 허용합니다.

### **수식**
$$
LeakyReLU(x) = \begin{cases}
x & \text{if } x > 0 \\
\alpha x & \text{if } x \leq 0
\end{cases} $$
여기서, $\alpha$는 음수 입력에 대한 기울기입니다.

### **요구 사항**
- `torch.max()` 함수를 사용하여 Leaky ReLU 활성화 함수를 구현해야 합니다.
- PyTorch의 내장된 활성화 함수(`torch.nn.LeakyReLU`)를 사용하지 않고, 수식을 기반으로 직접 구현해야 합니다.
- 기본적인 음수 기울기 값인 alpha 매개변수를 가지며 0.01로 설정되어 있습니다.

In [ ]:
# [답안 작성]
# ================================================================== #
def activation_function(x, alpha=0.01):

# ================================================================== #


In [ ]:
# [답안 검증] - 결과가 다르더라도 값이 정상적으로 출력되면 문제가 채점됩니다. 값이 출력되지 않으면 채점 대상에서 제외되니 [답안 작성] 코드 셀을 확인하세요.
x = torch.Tensor([-1, 0, 1])
y = activation_function(x)
y # 출력 결과 : tensor([-0.0100,  0.0000,  1.0000])

tensor([-0.0100,  0.0000,  1.0000])

# **문제2. `DataLoader` 구현**

### **문제 설명**
- 인공 신경망 학습에서 데이터는 배치(batch) 단위로 모델에 입력되어야 합니다. PyTorch에서는 이를 쉽게 처리하기 위해 DataLoader라는 도구를 제공합니다. DataLoader는 데이터셋을 로드하고, 배치 단위로 모델에 전달하여 학습을 돕는 중요한 역할을 합니다. Pytorch를 이용하여 사용자 데이터셋과 DataLoader를 생성하세요.

### **요구사항**
- `CustomDataSet` 클래스를 구현하세요.
  - `__init__`, `__len__`, `__getitem__` 함수를 구현하세요.
- 구현한 `CustomDataSet` 클래스를 이용하여 `dataset` 변수를 생성하고 `dataloader`를 생성하세요.
  - `dataset` 변수 생성에 사용되는 데이터는 `datas`와 `labels`입니다.
- `dataloader`의 배치 크기를 32으로 설정하고, 데이터를 순서대로 가져오도록 하세요. 마지막 배치는 생략하지 않습니다.

In [ ]:
# [코드 제공]
torch.manual_seed(42)
datas = torch.randn(200, 2)        # 2차원 텐서 (정형 데이터)
labels = torch.randn((200,))       # 1차원 텐서 (수 예측을 위한 레이블)
datas.shape, labels.shape

(torch.Size([200, 2]), torch.Size([200]))

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
# ================================================================== # - 이 주석을 삭제하지 마세요.
class CustomDataset(Dataset):

# ================================================================== # - 이 주석을 삭제하지 마세요.

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
# ================================================================== # - 이 주석을 삭제하지 마세요.
dataset =
data_loader =
# ================================================================== # - 이 주석을 삭제하지 마세요.

In [ ]:
# [답안 검증] - 결과가 다르더라도 값이 정상적으로 출력되면 문제가 채점됩니다. 값이 출력되지 않으면 채점 대상에서 제외되니 [답안 작성] 코드 셀을 확인하세요.
torch.manual_seed(42)
data_iter = iter(data_loader)
batch_data, batch_labels = next(data_iter)
print(f"첫 번째 배치 데이터 크기 : {batch_data.shape}")
print(f"첫 번째 배치 레이블 크기 : {batch_labels.shape}")
print(f"첫 번째 배치, 첫 번째 데이터 : {batch_data[0]}")
print(f"첫 번째 배치, 첫 번째 레이블: {batch_labels[0]}")

첫 번째 배치 데이터 크기 : torch.Size([32, 2])
첫 번째 배치 레이블 크기 : torch.Size([32])
첫 번째 배치, 첫 번째 데이터 : tensor([1.9269, 1.4873])
첫 번째 배치, 첫 번째 레이블: 0.024699924513697624


# **문제3. `합성곱 신경망` 구현**

### **문제 설명**
- Convolutional Neural Network (CNN)은 이미지 데이터의 특징을 추출하고 분류하는 데 매우 효과적인 모델입니다. PyTorch를 사용하여 CNN 모델을 구현하세요. (학습은 진행하지 않습니다.)

### **요구사항**
- CNN 모델을 설계하시오. 모델은 다음 구조를 따라야 합니다.
    - 입력 데이터 형태: (batch, 3, 32, 32)
      - 32x32 크기를 가지는 컬러이미지(RGB)를 입력으로 가정합니다.
    - 첫 번째 컨볼루션 층(`conv1`): 3개의 입력 채널과 32개의 출력 채널, 커널 크기 3x3, 패딩 1, 스트라이드 1
    - 두 번째 컨볼루션 층(`conv2`): 32개의 입력 채널과 64개의 출력 채널, 커널 크기 3x3, 패딩 1, 스트라이드 1
    - 풀링 층(`pool`): Max Pooling, 크기 2x2, 스트라이드 2
      - 풀링 층은 두 번째 컨볼루션 이후 에만 적용합니다.
    - 평탄화 층(`flatten`)
      - `Flatten` 레이어를 사용하세요.
    - 완전 연결층 (Fully Connected Layer): 은닉층 2개(`fc1`, `fc2`)와 출력층(`fc3`) 1개를 추가하세요. 은닉층 `fc1`은 1024개, 은닉층 `fc2`는 512개의 뉴런을 가지며 출력층 `fc3`은 1개의 뉴런을 갖도록 구성하세요.
    - 모든 은닉층(완전 연결층 및 컨볼루션 층 포함) 활성화 함수로는 ReLU를 사용하세요.
      - `nn.ReLU`, `torch.ReLU` 모두 사용 가능합니다.
    - 출력층 활성화 함수는 Sigmoid로 지정하세요.
      - `nn.Sigmoid`, `torch.sigmoid` 모두 사용가능합니다.
- 모델 구성은 nn.Sequential 혹은 nn.Module 중 자유롭게 선택하면 됩니다.
    - nn.Module을 사용하는 경우 `__init__()` 함수에서 아래의 코드를 초기화 코드로 사용하세요. (이외의 초기화 방법을 사용하는 경우 오답 처리)
        - **`super().__init__()`**
- 모델 학습 및 손실 함수는 구현할 필요 없으며, CNN 모델 구현에만 집중하세요.
- **`model` 변수에 구현한 모델을 저장하세요.**

```
=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
CNN                                      --
├─Conv2d: 1-1                            896
├─Conv2d: 1-2                            18,496
├─MaxPool2d: 1-3                         --
├─Flatten: 1-4                           --
├─Linear: 1-5                            16,778,240
├─Linear: 1-6                            524,800
├─Linear: 1-7                            513
=================================================================
Total params: 17,322,945
Trainable params: 17,322,945
Non-trainable params: 0
=================================================================
```

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
torch.manual_seed(42) # 재현성 확보를 위해 삭제하지 마세요.
# ================================================================== # - 이 주석을 삭제하지 마세요.


# nn.Module 방식을 사용하는 경우 아래의 코드를 주석 해제 후 사용 (nn.Sequential을 사용하는 경우 주석 삭제)
# class CNN(nn.Module):
#     def __init__(self):
#         super().__init__()

model =
summary(model)
# ================================================================== # - 이 주석을 삭제하지 마세요.

Layer (type:depth-idx)                   Param #
CNN                                      --
├─Conv2d: 1-1                            896
├─Conv2d: 1-2                            18,496
├─MaxPool2d: 1-3                         --
├─Flatten: 1-4                           --
├─Linear: 1-5                            16,778,240
├─Linear: 1-6                            524,800
├─Linear: 1-7                            513
Total params: 17,322,945
Trainable params: 17,322,945
Non-trainable params: 0

In [ ]:
# [답안 검증] - 결과가 다르더라도 값이 정상적으로 출력되면 문제가 채점됩니다. 값이 출력되지 않으면 채점 대상에서 제외되니 [답안 작성] 코드 셀을 확인하세요.

# 모든 값이 1로 채워진 1, 3, 32, 32 형태의 텐서 생성
input_tensor = torch.ones((1, 3, 32, 32))

# 모델에 입력하여 피드포워드 실행
output = model(input_tensor)
output

tensor([[0.5072]], grad_fn=<SigmoidBackward0>)

# **문제4. `순환 신경망` 구현**

### **문제 설명**
- LSTM(Long Short-Term Memory)은 순차 데이터를 처리하고, 장기 의존성을 다루는 데 탁월한 성능을 보이는 순환 신경망(RNN)의 한 종류입니다. 이번 과제에서는 PyTorch의 LSTM 레이어를 사용하여 별점(1~5)을 예측하는 모델을 구현하세요.

### **요구사항**

- 모델은 1개의 Embedding 레이어(`embedding`), 1개의 LSTM 레이어(`lstm`), 1개의 출력층인 Fully Connected Layer(`fc`)을 가집니다.
- `__init__`에서 정의한 매개변수를 활용하여 모델을 작성하세요.
- 주요 사항은 다음과 같습니다:
  - **입력 데이터**:
    - 크기는 `(batch_size, 시퀀스 길이)`입니다.
    - **단어 사전의 크기**는 500입니다.
    - **임베딩 차원**은 32으로 설정됩니다.
  - **LSTM 레이어**:
    - **은닉 상태(hidden state)** 의 크기는 16로 설정됩니다.
    - 모든 시퀀스를 출력한 후 **마지막 시퀀스를 선택**하여 예측에 사용됩니다.
  - **출력층**:
    - Fully Connected Layer는 은닉 상태에서 마지막 시퀀스를 입력으로 받아 5개의 출력을 생성합니다.
- 모델 학습 및 손실 함수는 구현할 필요 없으며, RNN 모델 구현에만 집중하세요.
- **`model` 변수에 구현한 모델을 저장하세요.**

```
=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
RNN                                      --
├─Embedding: 1-1                         16,000
├─LSTM: 1-2                              3,200
├─Linear: 1-3                            85
=================================================================
Total params: 19,285
Trainable params: 19,285
Non-trainable params: 0
=================================================================
```

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
torch.manual_seed(42) # 재현성 확보를 위해 삭제하지 마세요.
# ================================================================== # - 이 주석을 삭제하지 마세요.
class RNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim): # __init__ 함수의 매개변수를 수정하지 마세요.
        super().__init__()


model =
summary(model)
# ================================================================== # - 이 주석을 삭제하지 마세요.


Layer (type:depth-idx)                   Param #
RNN                                      --
├─Embedding: 1-1                         16,000
├─LSTM: 1-2                              3,200
├─Linear: 1-3                            85
Total params: 19,285
Trainable params: 19,285
Non-trainable params: 0

In [ ]:
# [답안 검증] - 결과가 다르더라도 값이 정상적으로 출력되면 문제가 채점됩니다. 값이 출력되지 않으면 채점 대상에서 제외되니 [답안 작성] 코드 셀을 확인하세요.
torch.manual_seed(42)
random_data_point = torch.randint(0, 500, (1, 7))

# 모델에 입력하여 피드포워드 실행
output = model(random_data_point)
output

tensor([[ 0.0722,  0.2188,  0.0011,  0.1804, -0.0047]],
       grad_fn=<AddmmBackward0>)

# **문제5. `심층 신경망` 구현 (전복 나이 예측 데이터셋)**

### **문제 설명**
- 심층 신경망은 여러 개의 은닉층을 갖는 신경망으로, 다양한 비선형 변환을 통해 복잡한 데이터 패턴을 학습할 수 있습니다.
- 전복 나이를 예측 하는 심층 신경망(Deep Neural Network, DNN)을 구현하세요.
  
### **요구 사항**
- 전복 나이 예측 데이터셋은 JAEN 모듈의 `load_data()` 함수로 불러올 수 있으며, 8개의 특성(feature)을 가진 데이터입니다.
  - 회귀 문제 입니다.
- 학습 및 평가는 제공된 `train_loader`와 `test_loader`를 사용하세요.
- 심층 신경망 모델 구조 및 구현 방식은 자유롭게 진행하되, `model` 변수에 저장하세요.
  - 손실 함수에 맞는 출력층의 뉴런 수와 활성화 함수를 지정하세요.
- 손실 함수로 `MSELoss`(평균 제곱 오차)를 사용하고 `criterion`변수에, 옵티마이저로 `Adam`을 사용하여 `optimizer`변수에 저장하세요.
- 모델을 10 에포크 동안 학습시키고, 각 에포크에서의 손실을 출력하세요.
  - `running_loss / len(train_loader)`
- 평가 데이터(`test_loader`)의 평균 제곱 오차(MSE)를 계산하고, 최종 MSE를 출력하세요.
  - `total_loss / len(test_loader)`

In [ ]:
# [제공 코드] - 이 코드를 실행하세요.
from JAEN.datasets import load_data
train_loader, test_loader = load_data('abalone')
x, y = next(iter(train_loader))
x.shape, y.shape

(torch.Size([32, 8]), torch.Size([32]))

- 심층 신경망 모델 구조 및 구현 방식은 자유롭게 진행하되, `model` 변수에 저장하세요.

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
# 모델 생성 (아래 구조는 예시로 꼭 따라할 필요는 없습니다.)
# ================================================================== # - 이 주석을 삭제하지 마세요.

# nn.Module 방식을 사용하는 경우 아래의 코드를 주석 해제 후 사용 (nn.Sequential을 사용하는 경우 주석 삭제)
# class DNN(nn.Module):
#     def __init__(self):
#         super().__init__()


# ================================================================== # - 이 주석을 삭제하지 마세요.

Layer (type:depth-idx)                   Param #
DNN                                      --
├─Linear: 1-1                            576
├─Linear: 1-2                            2,080
├─Linear: 1-3                            33
├─ReLU: 1-4                              --
Total params: 2,689
Trainable params: 2,689
Non-trainable params: 0

- 손실 함수로 `MSELoss`(평균 제곱 오차)를 사용하고 `criterion`변수에, 옵티마이저로 `Adam`을 사용하여 `optimizer`변수에 저장하세요.

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
#  손실함수 및 옵티마이저 정의
# ================================================================== # - 이 주석을 삭제하지 마세요.
criterion =
optimizer =
# ================================================================== # - 이 주석을 삭제하지 마세요.

- 모델을 10 에포크 동안 학습시키고, 각 에포크에서의 손실을 출력하세요.
  - `running_loss / len(train_loader)`

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
# 학습 과정 코드 작성
# ================================================================== # - 이 주석을 삭제하지 마세요.
epochs = 10
for epoch in range( {코드작성} ): # epochs 변수의 값 만큼 반복
    running_loss = 0.0

    {코드작성}  # 모델을 학습모드로 설정

    for inputs, labels in train_loader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        # inputs에 대한 출력값(outputs) 계산
        outputs = {코드작성}

        # 출력값(outputs)과 정답값(labels)의 손실 계산
        loss =  {코드작성}

        # 이전 계산된 기울기를 0으로 초기화
        {코드작성}

        # 손실(loss)에 대한 각 파라미터의 기울기(gradient)를 계산
        {코드작성}

        # 계산된 기울기를 사용하여 각 파라미터를 업데이트
        {코드작성}

        running_loss += loss.item()

    print(f'Epoch {epoch+1}, Loss: {코드작성}') # 에폭별 손실 값 출력
# ================================================================== # - 이 주석을 삭제하지 마세요.

Epoch 1, Loss: 57.856538754417784
Epoch 2, Loss: 16.63206169037592
Epoch 3, Loss: 11.736752644039335
Epoch 4, Loss: 11.289893254779635
Epoch 5, Loss: 10.995917079562233
Epoch 6, Loss: 10.864002686455136
Epoch 7, Loss: 10.67661342166719
Epoch 8, Loss: 10.647358124596732
Epoch 9, Loss: 10.510563537052699
Epoch 10, Loss: 10.4725695337568


- 평가 데이터(`test_loader`)의 평균 제곱 오차(MSE)를 계산하고, 최종 MSE를 출력하세요.
  - `total_loss / len(test_loader)`

In [ ]:
# [답안 작성] - 이 주석을 삭제하지 마세요.
# 평가 과정 코드 작성
# ================================================================== # - 이 주석을 삭제하지 마세요.

{코드작성} # 모델을 평가모드로 설정

total_loss = 0.0
with {코드작성} : # 기울기 계산을 비활성화
    for inputs, labels in test_loader:
        inputs = inputs.to(device)        # 데이터를 device로 이동
        labels = labels.to(device)        # 데이터를 device로 이동

        # inputs에 대한 출력값(outputs) 계산
        outputs = {코드작성}

        # 출력값(outputs)과 정답값(labels)의 손실 계산
        loss =  {코드작성}

        # 각 배치별 손실값 추가
        total_loss += loss.item()

    # 평균 제곱 오차 (MSE) 계산
    print(f'Loss: {코드작성}')
# ================================================================== # - 이 주석을 삭제하지 마세요.

Loss: 10.684541684609872


# 수고하셨습니다. 파일 이름의 '반' 부분은 본인의 반, 'OOO' 부분을 본인의 성함으로 변경하여 저장한 후, 평가 시스템에 제출해주시면 됩니다.